type APIExceptionCode =
    | 'INAPPROPRIATE_PAYLOAD'
    | 'INAPPROPRIATE_DEPTH'
    | 'NO_PARENT'
    | 'ALREADY_EXEIST'
    | 'FAIL_EXEIT'
    | 'NO_EXEIST_BUBBLE'
    | 'NOT_EXIST'
    | 'ALREADY_EXIST'
    | 'NOT_MATCH_PASSWORD'
    | 'SIGN_UP_NEEDED'
    | 'MEMBER_EXISTS'
    | 'USER_NOT_FOUND'
    | 'WORKSPACE_NOT_FOUND'
    | 'NOT_SUPPORTED'
    | 'FILE_TOO_LARGE'
    | 'FILE_NOT_FOUND'
    | 'FORBIDDEN';

type Provider = 'KAKAO' | 'GOOGLE';
